server:
  port: 8900
spring:
    application:
        name: api-gateway
    cloud:
      gateway:
        discovery:
          locator:
            enabled: true
            lower-case-service-id: true
        routes:
          - id: user-service
            uri: lb://users
            predicates:
              - Path=/users/**
            filters:
              - RewritePath=/users/(?<remaining>.*), /${remaining}
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/