server:
  port: 8500
spring:
  graphql:
    graphiql:
      enabled: true
      path: /playground
  application:
    name: users
  datasource:
    url: jdbc:mysql://localhost:3306/flourimus_users
    username: root
    password: password@123
    driver-class-name: com.mysql.cj.jdbc.Driver
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
