server:
  port: 8500
spring:
  graphql:
    graphiql:
      enabled: true
      path: /playground
  application:
    name: users
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
